config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :debts
  resources :debtors
  devise_for :users
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/debtor.rb
class Debtor < ApplicationRecord
  belongs_to :user

  has_many :payments
  has_many :debts
end

app/controllers/debtors_controller.rb
class DebtorsController < ApplicationController
  before_action :set_debtor, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /debtors
  # GET /debtors.json
  def index
    @debtors = Debtor.where(:user_id => current_user.id).all
  end

  # GET /debtors/1
  # GET /debtors/1.json
  def show
    @user = User.where(:user_id => current_user.id)
    @debtor = Debtor.find(params[:id])
  end

  # GET /debtors/new
  def new
    @debtor = current_user.debtors.build
  end

  # GET /debtors/1/edit
  def edit
  end

  # POST /debtors
  # POST /debtors.json
  def create
    @debtor = current_user.debtors.build(debtor_params)

    respond_to do |format|
      if @debtor.save
        format.html { redirect_to @debtor, notice: 'Debtor was successfully created.' }
        format.json { render :show, status: :created, location: @debtor }
      else
        format.html { render :new }
        format.json { render json: @debtor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /debtors/1
  # PATCH/PUT /debtors/1.json
  def update
    respond_to do |format|
      if @debtor.update(debtor_params)
        format.html { redirect_to @debtor, notice: 'Debtor was successfully updated.' }
        format.json { render :show, status: :ok, location: @debtor }
      else
        format.html { render :edit }
        format.json { render json: @debtor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /debtors/1
  # DELETE /debtors/1.json
  def destroy
    @debtor.destroy
    respond_to do |format|
      format.html { redirect_to debtors_url, notice: 'Debtor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_debtor
      @debtor = Debtor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def debtor_params
      params.require(:debtor).permit(:name, :number, :user_id)
    end
end

app/helpers/debtors_helper.rb
module DebtorsHelper
end

app/views/debtors/_form.html.erb
<%= form_with(model: debtor, local: true) do |form| %>
  <% if debtor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(debtor.errors.count, "error") %> prohibited this debtor from being saved:</h2>

      <ul>
        <% debtor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/debtors/edit.html.erb
<h1>Editing Debtor</h1>

<%= render 'form', debtor: @debtor %>

<%= link_to 'Show', @debtor %> |
<%= link_to 'Back', debtors_path %>

app/views/debtors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Debtors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @debtors.each do |debtor| %>
      <tr>
        <td><%= debtor.name %></td>
        <td><%= debtor.number %></td>
        <td><%= debtor.user_id %></td>
        <td><%= link_to 'Show', debtor %></td>
        <td><%= link_to 'Edit', edit_debtor_path(debtor) %></td>
        <td><%= link_to 'Destroy', debtor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Debtor', new_debtor_path %>

app/views/debtors/new.html.erb
<h1>New Debtor</h1>

<%= render 'form', debtor: @debtor %>

<%= link_to 'Back', debtors_path %>

app/views/debtors/show.html.erb
<p id="notice"><%= notice %></p>


  <strong>Name:</strong>
  <%= @debtor.name %> <%= @debtor.number %>
<br>


<h3>Debts</h3>
<% @debtor.debts.each do |debt| %>
	<%= link_to debt.amount, debt %>
	<%= debt.reason %>
	<%= debt.date %> <br>
	<b>Debts Paid <%= debt.payments.count %></b><br>
	<% debt.payments.each do |payment| %>
		<%= payment.amount %>
		<%= payment.method %>
		<%= payment.date  %>
		<br>
	<% end %>
	<br>
	Total Paid 
<% end %>

<h3>Payments</h3>
	<% @debtor.payments.each do |payment| %>
		<%#= payment.project.name %>
		Ksh <%= payment.amount %>
		<%= payment.date %>
		<%= payment.method %><br>
	<% end %>
	<br>
	Total Payments : <%#= @debtor.totalpayments %><br>
	Debt Balance : <%#= @debtor.amount - @debtor.totalpayments %>


<br>
<br>
<%= link_to 'Edit', edit_debtor_path(@debtor) %> |
<%= link_to 'Delete', @debtor, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', debtors_path %> 