config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :debts
  resources :debtors
  devise_for :users
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :debt
  belongs_to :debtor
  belongs_to :user
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.where(:user_id => current_user.id).order('created_at DESC')
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = current_user.payments.build
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = current_user.payments.build(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def payment_params
      params.require(:payment).permit(:amount, :method, :debt_id, :debtor_id, :user_id)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_for(payment) do |f| %>
  <% if payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :Debtor %>
    <%= f.collection_select :debtor_id, Debtor.where(:user_id => current_user.id), :id, :name, include_blank: true %>
  </div>

  <div class="field">
    <%= f.label :Debt %>
    <%#= f.collection_select :debt_id, Debt.where(:user_id => current_user.id), :id, :reason %>

    <%= f.grouped_collection_select :debt_id, Debtor.order(:name), :debts, :name, :id, :reason, include_blank: true %>
    <%#= f.grouped_collection_select :state_id, Country.order(:name), :states, :name, :id, :name, include_blank: true %>
    <%#= f.grouped_collection_select :whatYouNeedToSelect_id, ParentModel.order(:name), :controller of what you selecting, :field from parent model, :id, :fiel you are selecting, include_blank: true %>



  </div>

  <div class="field">
    <%= f.label :amount %>
    <%= f.number_field :amount %>
  </div>

  <div class="field">
    <%= f.label :method %>
    <%= f.text_field :method %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.date_select :date %>
  </div>

<!--   <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>
 -->

  <div class="actions">
    <%= f.submit 'Make Payment' %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payments</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Method</th>
      <th>Debt</th>
      <th>Debtor</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.amount %></td>
        <td><%= payment.method %></td>
        <td><%= payment.debt_id %></td>
        <td><%= payment.debtor_id %></td>
        <td><%= payment.user_id %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @payment.amount %>
</p>

<p>
  <strong>Method:</strong>
  <%= @payment.method %>
</p>

<p>
  <strong>Debt:</strong>
  <%= @payment.debt_id %>
</p>

<p>
  <strong>Debtor:</strong>
  <%= @payment.debtor_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @payment.user_id %>
</p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>